
# REQUEST EXAMPLE
POST http://localhost:7700/user_authentication/
Content-Type: application/json

{
    "user": "user0",
    "pass": "pass0"
}

###

GET http://localhost:7700/example/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY4NDg2NDIsImV4cCI6MTU4Njg0ODk0Mn0.l987GYLnC2Y_EDzOue7gjcV-RIdwXxT80qswiiOTyBA

###

GET http://localhost:7700/example/11C7D9C9B9175087A7A2F0FC37033349
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY4NDg2NDIsImV4cCI6MTU4Njg0ODk0Mn0.l987GYLnC2Y_EDzOue7gjcV-RIdwXxT80qswiiOTyBA

###
POST http://localhost:7700/example/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY4NDg2NDIsImV4cCI6MTU4Njg0ODk0Mn0.l987GYLnC2Y_EDzOue7gjcV-RIdwXxT80qswiiOTyBA
Content-Type: application/json

{
    "text": "9999年"
}

###
DELETE http://localhost:7700/example/22152A85933D19A2DFE49E43543FA92C/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY4NDg2NDIsImV4cCI6MTU4Njg0ODk0Mn0.l987GYLnC2Y_EDzOue7gjcV-RIdwXxT80qswiiOTyBA