
# REQUEST EXAMPLE
POST http://localhost:7700/user_authentication/
Content-Type: application/json

{
    "user": "user0",
    "pass": "pass0"
}

###

GET http://localhost:7700/example/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY3NzAzNDYsImV4cCI6MTU4Njc3MDY0Nn0.kxZe-m_RcbGEyXnM2aOegahQOvg_ItwA5z2OsGLdLdE


###
POST http://localhost:7700/example/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY3NjcyNzUsImV4cCI6MTU4Njc2NzU3NX0.Oja1x_rRQ_DApQSZ4AGPRM2No7q5uTn9QRX-ygDPhKA
Content-Type: application/json

{
    "text": "2023年"
}

###
DELETE http://localhost:7700/example/9CA4DEC5E092EF90AE4020D/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY3NzA1MTMsImV4cCI6MTU4Njc3MDgxM30.NNhB64441-gSapmoA6XW2TggMbpBELeLjH2HLpWJJB8