
# REQUEST EXAMPLE
POST http://localhost:7700/user_authentication/
Content-Type: application/json

{
    "user": "user0",
    "pass": "pass0"
}

###

GET http://localhost:7700/get_item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY0MTY5NzAsImV4cCI6MTU4NjQxNzI3MH0.fCb5QBuaAevR_hrGwdZVeoM6fBM6ZIKooYfUqQXHwu4


###
POST http://localhost:7700/post_item/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlcjAiLCJpYXQiOjE1ODY0MTcxMjUsImV4cCI6MTU4NjQxNzQyNX0.SPYBE8zHyWMguyCaNrRkaE-QN4h6h-GbnjJVl7y9BRI
Content-Type: application/json

{
    "text": "success"
}